name: placars_savt
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  #State management 
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5

  #Cache 
  hive: ^2.2.3
  hive_flutter: ^1.1.0  
  shared_preferences: ^2.1.0


  #Networking
  connectivity_plus: ^3.0.6
  dio: ^5.1.1

  #Language
  localization: ^2.1.0

  #core
  json_annotation: ^4.8.1
  equatable: ^2.0.5

  #splash
  flutter_native_splash: ^2.2.9
  easy_localization: ^3.0.1
  
  #widgets 
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.4.0
  lottie: ^2.3.2

  #firebase
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0
  firestore_ui: ^1.25.1
  image_picker: ^0.8.7+5
  


flutter_native_splash:
  color: "#fffaf5"
  image: "asset/image/splash.png"
  android: true
  ios: true
  remove_alpha_ios: true
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  hive_generator: ^2.0.0
  json_serializable: ^6.6.2

flutter:

  uses-material-design: true
     
  assets:
    - asset/image/
    - asset/lang/
    - asset/svg/
    - asset/lotties/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
